// A catalogue of staple foods, offered in the "add food" search alongside the user's own library.
//
// Why it exists: a new journal starts with an empty library, so logging rice meant scanning a
// packet or typing four macros by hand — for food that has the same numbers in every kitchen.
// These are the ones worth having on tap.
//
// Values are per 100 g, from standard composition tables, for the food AS EATEN — cooked where it
// is eaten cooked, which is why the names say so. Dry pasta is 350 kcal and cooked pasta is 130;
// picking the wrong one is a threefold error, so the state is part of the name rather than left
// to the reader.
//
// Picking one copies it into the user's own foods (POST /api/foods dedupes by name), so from the
// second time on it behaves exactly like anything else they have logged.
// Display groups, by nutritional role rather than by botanical family: what you reach for when a
// day is short on protein, on carbs or on good fats. Pulses get their own group instead of being
// filed under protein or starch — they are both, and hiding that in either bucket loses it.
export const BASE_FOOD_GROUPS = {
  proteines: ['viandes', 'poissons'],
  feculents: ['cereales'],
  legumineuses: ['legumineuses'],
  legumes: ['legumes'],
  fruits: ['fruits'],
  bonnes_graisses: ['noix_graines', 'huiles'],
  laitiers: ['laitiers'],
  plats: ['divers'],
  boissons: ['boissons'],
  condiments: ['condiments'],
};

export function groupOfCategory(cat) {
  for (const [group, cats] of Object.entries(BASE_FOOD_GROUPS)) {
    if (cats.includes(cat)) return group;
  }
  return 'condiments';
}

export const BASE_FOODS = [
  // --- Féculents & céréales ---
  { name: 'Riz blanc cuit', kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, cat: 'cereales' },
  { name: 'Riz complet cuit', kcal: 112, protein: 2.6, carbs: 23, fat: 0.9, fiber: 1.8, cat: 'cereales' },
  { name: 'Pâtes cuites', kcal: 131, protein: 5, carbs: 25, fat: 1.1, fiber: 1.8, cat: 'cereales' },
  { name: 'Pâtes complètes cuites', kcal: 124, protein: 5.3, carbs: 27, fat: 0.5, fiber: 3.9, cat: 'cereales' },
  { name: 'Quinoa cuit', kcal: 120, protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, cat: 'cereales' },
  { name: 'Semoule / couscous cuit', kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, cat: 'cereales' },
  { name: 'Boulgour cuit', kcal: 83, protein: 3.1, carbs: 19, fat: 0.2, fiber: 4.5, cat: 'cereales' },
  { name: 'Pomme de terre cuite', kcal: 87, protein: 2, carbs: 20, fat: 0.1, fiber: 1.8, cat: 'legumes' },
  { name: 'Patate douce cuite', kcal: 90, protein: 2, carbs: 21, fat: 0.2, fiber: 3.3, cat: 'legumes' },
  { name: 'Pain complet', kcal: 247, protein: 13, carbs: 41, fat: 3.4, fiber: 7, cat: 'cereales' },
  { name: 'Pain blanc / baguette', kcal: 270, protein: 9, carbs: 55, fat: 1.5, fiber: 2.7, cat: 'cereales' },
  { name: 'Flocons d\'avoine', kcal: 379, protein: 13, carbs: 67, fat: 6.5, fiber: 10, cat: 'cereales' },
  { name: 'Muesli sans sucre ajouté', kcal: 375, protein: 10, carbs: 60, fat: 9, fiber: 8, cat: 'cereales' },
  { name: 'Galettes de riz', kcal: 387, protein: 8, carbs: 81, fat: 3, fiber: 4, cat: 'cereales' },
  { name: 'Tortilla de blé', kcal: 310, protein: 8, carbs: 51, fat: 8, fiber: 3, cat: 'cereales' },

  // --- Légumineuses ---
  { name: 'Lentilles cuites', kcal: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 7.9, cat: 'legumineuses' },
  { name: 'Pois chiches cuits', kcal: 164, protein: 8.9, carbs: 27, fat: 2.6, fiber: 7.6, cat: 'legumineuses' },
  { name: 'Haricots rouges cuits', kcal: 127, protein: 8.7, carbs: 23, fat: 0.5, fiber: 7.4, cat: 'legumineuses' },
  { name: 'Haricots blancs cuits', kcal: 139, protein: 9.7, carbs: 25, fat: 0.4, fiber: 10.5, cat: 'legumineuses' },
  { name: 'Pois cassés cuits', kcal: 118, protein: 8.3, carbs: 21, fat: 0.4, fiber: 8.3, cat: 'legumineuses' },
  { name: 'Tofu nature', kcal: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, cat: 'legumineuses' },
  { name: 'Tempeh', kcal: 192, protein: 20, carbs: 8, fat: 11, fiber: 0, cat: 'legumineuses' },
  { name: 'Houmous', kcal: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, cat: 'legumineuses' },

  // --- Viandes & œufs ---
  { name: 'Blanc de poulet cuit', kcal: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, cat: 'viandes' },
  { name: 'Cuisse de poulet cuite', kcal: 209, protein: 26, carbs: 0, fat: 11, fiber: 0, cat: 'viandes' },
  { name: 'Escalope de dinde cuite', kcal: 135, protein: 30, carbs: 0, fat: 1.2, fiber: 0, cat: 'viandes' },
  { name: 'Steak de bœuf 5% cuit', kcal: 170, protein: 27, carbs: 0, fat: 6.5, fiber: 0, cat: 'viandes' },
  { name: 'Bœuf haché 15% cuit', kcal: 250, protein: 26, carbs: 0, fat: 16, fiber: 0, cat: 'viandes' },
  { name: 'Filet de porc cuit', kcal: 175, protein: 30, carbs: 0, fat: 5.5, fiber: 0, cat: 'viandes' },
  { name: 'Jambon blanc', kcal: 107, protein: 18, carbs: 1, fat: 3.5, fiber: 0, cat: 'viandes' },
  { name: 'Œuf entier', kcal: 143, protein: 12.6, carbs: 0.7, fat: 9.5, fiber: 0, cat: 'viandes' },
  { name: 'Blanc d\'œuf', kcal: 52, protein: 11, carbs: 0.7, fat: 0.2, fiber: 0, cat: 'viandes' },

  // --- Poissons ---
  { name: 'Saumon cuit', kcal: 208, protein: 22, carbs: 0, fat: 13, fiber: 0, cat: 'poissons' },
  { name: 'Cabillaud cuit', kcal: 105, protein: 23, carbs: 0, fat: 0.9, fiber: 0, cat: 'poissons' },
  { name: 'Thon en boîte au naturel', kcal: 116, protein: 26, carbs: 0, fat: 1, fiber: 0, cat: 'poissons' },
  { name: 'Sardines à l\'huile égouttées', kcal: 208, protein: 25, carbs: 0, fat: 11, fiber: 0, cat: 'poissons' },
  { name: 'Maquereau cuit', kcal: 262, protein: 24, carbs: 0, fat: 18, fiber: 0, cat: 'poissons' },
  { name: 'Crevettes cuites', kcal: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, cat: 'poissons' },
  { name: 'Truite cuite', kcal: 190, protein: 27, carbs: 0, fat: 8.5, fiber: 0, cat: 'poissons' },

  // --- Produits laitiers ---
  { name: 'Lait demi-écrémé', kcal: 46, protein: 3.3, carbs: 4.8, fat: 1.6, fiber: 0, cat: 'laitiers' },
  { name: 'Lait entier', kcal: 64, protein: 3.2, carbs: 4.7, fat: 3.6, fiber: 0, cat: 'laitiers' },
  { name: 'Yaourt nature', kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, cat: 'laitiers' },
  { name: 'Yaourt grec 0%', kcal: 59, protein: 10, carbs: 3.6, fat: 0.4, fiber: 0, cat: 'laitiers' },
  { name: 'Skyr', kcal: 63, protein: 11, carbs: 4, fat: 0.2, fiber: 0, cat: 'laitiers' },
  { name: 'Fromage blanc 3%', kcal: 74, protein: 7.5, carbs: 4, fat: 3, fiber: 0, cat: 'laitiers' },
  { name: 'Cottage cheese', kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, fiber: 0, cat: 'laitiers' },
  { name: 'Mozzarella', kcal: 280, protein: 22, carbs: 2.2, fat: 20, fiber: 0, cat: 'laitiers' },
  { name: 'Comté / gruyère', kcal: 410, protein: 27, carbs: 0.5, fat: 33, fiber: 0, cat: 'laitiers' },
  { name: 'Parmesan', kcal: 392, protein: 36, carbs: 3.2, fat: 25, fiber: 0, cat: 'laitiers' },
  { name: 'Beurre', kcal: 750, protein: 0.7, carbs: 0.6, fat: 83, fiber: 0, cat: 'laitiers' },
  { name: 'Boisson d\'amande sans sucre', kcal: 14, protein: 0.5, carbs: 0.3, fat: 1.2, fiber: 0.3, cat: 'boissons' },
  { name: 'Boisson de soja nature', kcal: 43, protein: 3.3, carbs: 2.5, fat: 2.1, fiber: 0.5, cat: 'boissons' },

  // --- Légumes ---
  { name: 'Brocoli cuit', kcal: 35, protein: 2.4, carbs: 4, fat: 0.4, fiber: 3.3, cat: 'legumes' },
  { name: 'Haricots verts cuits', kcal: 35, protein: 1.9, carbs: 5, fat: 0.3, fiber: 3.4, cat: 'legumes' },
  { name: 'Courgette cuite', kcal: 17, protein: 1.2, carbs: 2.1, fat: 0.3, fiber: 1.1, cat: 'legumes' },
  { name: 'Carotte crue', kcal: 41, protein: 0.9, carbs: 8, fat: 0.2, fiber: 2.8, cat: 'legumes' },
  { name: 'Tomate', kcal: 18, protein: 0.9, carbs: 3.2, fat: 0.2, fiber: 1.2, cat: 'legumes' },
  { name: 'Concombre', kcal: 15, protein: 0.7, carbs: 3, fat: 0.1, fiber: 0.5, cat: 'legumes' },
  { name: 'Salade verte', kcal: 15, protein: 1.4, carbs: 1.7, fat: 0.2, fiber: 1.3, cat: 'legumes' },
  { name: 'Épinards cuits', kcal: 23, protein: 3, carbs: 1.4, fat: 0.4, fiber: 2.2, cat: 'legumes' },
  { name: 'Poivron rouge', kcal: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, cat: 'legumes' },
  { name: 'Oignon', kcal: 40, protein: 1.1, carbs: 9, fat: 0.1, fiber: 1.7, cat: 'legumes' },
  { name: 'Champignons de Paris', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, cat: 'legumes' },
  { name: 'Chou-fleur cuit', kcal: 23, protein: 1.8, carbs: 2.9, fat: 0.5, fiber: 2.3, cat: 'legumes' },
  { name: 'Aubergine cuite', kcal: 35, protein: 0.8, carbs: 6, fat: 0.2, fiber: 3, cat: 'legumes' },
  { name: 'Petits pois cuits', kcal: 84, protein: 5.4, carbs: 14, fat: 0.4, fiber: 5.1, cat: 'legumes' },
  { name: 'Avocat', kcal: 160, protein: 2, carbs: 2, fat: 15, fiber: 6.7, cat: 'fruits' },

  // --- Fruits ---
  { name: 'Banane', kcal: 89, protein: 1.1, carbs: 20, fat: 0.3, fiber: 2.6, cat: 'fruits' },
  { name: 'Pomme', kcal: 52, protein: 0.3, carbs: 12, fat: 0.2, fiber: 2.4, cat: 'fruits' },
  { name: 'Poire', kcal: 57, protein: 0.4, carbs: 13, fat: 0.1, fiber: 3.1, cat: 'fruits' },
  { name: 'Orange', kcal: 47, protein: 0.9, carbs: 9, fat: 0.1, fiber: 2.4, cat: 'fruits' },
  { name: 'Clémentine', kcal: 47, protein: 0.9, carbs: 11, fat: 0.2, fiber: 1.7, cat: 'fruits' },
  { name: 'Kiwi', kcal: 61, protein: 1.1, carbs: 12, fat: 0.5, fiber: 3, cat: 'fruits' },
  { name: 'Fraises', kcal: 32, protein: 0.7, carbs: 6, fat: 0.3, fiber: 2, cat: 'fruits' },
  { name: 'Framboises', kcal: 52, protein: 1.2, carbs: 8, fat: 0.7, fiber: 6.5, cat: 'fruits' },
  { name: 'Myrtilles', kcal: 57, protein: 0.7, carbs: 12, fat: 0.3, fiber: 2.4, cat: 'fruits' },
  { name: 'Raisin', kcal: 69, protein: 0.7, carbs: 17, fat: 0.2, fiber: 0.9, cat: 'fruits' },
  { name: 'Mangue', kcal: 60, protein: 0.8, carbs: 13, fat: 0.4, fiber: 1.6, cat: 'fruits' },
  { name: 'Ananas', kcal: 50, protein: 0.5, carbs: 12, fat: 0.1, fiber: 1.4, cat: 'fruits' },
  { name: 'Pastèque', kcal: 30, protein: 0.6, carbs: 7, fat: 0.2, fiber: 0.4, cat: 'fruits' },
  { name: 'Dattes', kcal: 282, protein: 2.5, carbs: 75, fat: 0.4, fiber: 8, cat: 'fruits' },
  { name: 'Compote sans sucre ajouté', kcal: 50, protein: 0.3, carbs: 11, fat: 0.1, fiber: 1.3, cat: 'fruits' },

  // --- Noix, graines & oléagineux ---
  { name: 'Amandes', kcal: 579, protein: 21, carbs: 9, fat: 50, fiber: 12, cat: 'noix_graines' },
  { name: 'Noix', kcal: 654, protein: 15, carbs: 7, fat: 65, fiber: 6.7, cat: 'noix_graines' },
  { name: 'Noix de cajou', kcal: 553, protein: 18, carbs: 27, fat: 44, fiber: 3.3, cat: 'noix_graines' },
  { name: 'Cacahuètes', kcal: 567, protein: 26, carbs: 16, fat: 49, fiber: 8.5, cat: 'noix_graines' },
  { name: 'Beurre de cacahuète', kcal: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, cat: 'noix_graines' },
  { name: 'Graines de chia', kcal: 486, protein: 17, carbs: 42, fat: 31, fiber: 34, cat: 'noix_graines' },
  { name: 'Graines de courge', kcal: 559, protein: 30, carbs: 11, fat: 49, fiber: 6, cat: 'noix_graines' },
  { name: 'Lin moulu', kcal: 534, protein: 18, carbs: 29, fat: 42, fiber: 27, cat: 'noix_graines' },

  // --- Matières grasses & condiments ---
  { name: 'Huile d\'olive', kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, cat: 'huiles' },
  { name: 'Huile de colza', kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, cat: 'huiles' },
  { name: 'Moutarde', kcal: 66, protein: 4, carbs: 5, fat: 3.5, fiber: 3, cat: 'condiments' },
  { name: 'Ketchup', kcal: 102, protein: 1.2, carbs: 24, fat: 0.2, fiber: 0.4, cat: 'condiments' },
  { name: 'Sauce soja', kcal: 53, protein: 8, carbs: 5, fat: 0.1, fiber: 0.8, cat: 'condiments' },
  { name: 'Miel', kcal: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0.2, cat: 'condiments' },
  { name: 'Confiture', kcal: 250, protein: 0.4, carbs: 60, fat: 0.1, fiber: 1, cat: 'condiments' },

  // --- Compléments & en-cas ---
  { name: 'Whey (poudre)', kcal: 380, protein: 78, carbs: 6, fat: 5, fiber: 0, cat: 'divers' },
  { name: 'Chocolat noir 70%', kcal: 598, protein: 7.8, carbs: 46, fat: 43, fiber: 11, cat: 'divers' },
  { name: 'Chocolat au lait', kcal: 535, protein: 7.6, carbs: 59, fat: 30, fiber: 3.4, cat: 'divers' },
  { name: 'Barre protéinée', kcal: 350, protein: 30, carbs: 35, fat: 9, fiber: 5, cat: 'divers' },
  { name: 'Chips', kcal: 536, protein: 7, carbs: 53, fat: 34, fiber: 4.4, cat: 'divers' },
  { name: 'Cacao en poudre non sucré', kcal: 228, protein: 20, carbs: 58, fat: 14, fiber: 33, cat: 'divers' },

  // --- Ajouts : variantes, plats courants, boissons ---
  { name: 'Riz basmati cuit', kcal: 121, protein: 2.7, carbs: 25, fat: 0.4, fiber: 0.5, cat: 'cereales' },
  { name: 'Riz sauvage cuit', kcal: 101, protein: 4, carbs: 21, fat: 0.3, fiber: 1.8, cat: 'cereales' },
  { name: 'Nouilles de riz cuites', kcal: 109, protein: 0.9, carbs: 25, fat: 0.2, fiber: 1, cat: 'cereales' },
  { name: 'Nouilles soba cuites', kcal: 99, protein: 5.1, carbs: 21, fat: 0.1, fiber: 0, cat: 'cereales' },
  { name: 'Polenta cuite', kcal: 70, protein: 1.6, carbs: 15, fat: 0.3, fiber: 0.8, cat: 'cereales' },
  { name: 'Gnocchi', kcal: 133, protein: 3.5, carbs: 27, fat: 1, fiber: 1.5, cat: 'cereales' },
  { name: 'Millet cuit', kcal: 119, protein: 3.5, carbs: 23, fat: 1, fiber: 1.3, cat: 'cereales' },
  { name: 'Sarrasin cuit', kcal: 92, protein: 3.4, carbs: 20, fat: 0.6, fiber: 2.7, cat: 'cereales' },
  { name: 'Épeautre cuit', kcal: 127, protein: 5.5, carbs: 26, fat: 0.8, fiber: 3.9, cat: 'cereales' },
  { name: 'Orge perlé cuit', kcal: 123, protein: 2.3, carbs: 28, fat: 0.4, fiber: 3.8, cat: 'cereales' },
  { name: 'Purée de pomme de terre', kcal: 83, protein: 2, carbs: 12, fat: 3, fiber: 1.3, cat: 'cereales' },
  { name: 'Frites au four', kcal: 165, protein: 3, carbs: 25, fat: 5.5, fiber: 3, cat: 'cereales' },
  { name: 'Frites (friture)', kcal: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, cat: 'cereales' },
  { name: 'Pain de mie', kcal: 265, protein: 8, carbs: 49, fat: 3.5, fiber: 2.5, cat: 'cereales' },
  { name: 'Pain aux céréales', kcal: 250, protein: 9, carbs: 40, fat: 5, fiber: 6, cat: 'cereales' },
  { name: 'Pain pita', kcal: 275, protein: 9, carbs: 55, fat: 1.2, fiber: 2.2, cat: 'cereales' },
  { name: 'Biscottes', kcal: 380, protein: 12, carbs: 72, fat: 4, fiber: 5, cat: 'cereales' },
  { name: 'Corn flakes', kcal: 357, protein: 7, carbs: 84, fat: 0.4, fiber: 3, cat: 'cereales' },
  { name: 'Granola', kcal: 450, protein: 9, carbs: 62, fat: 18, fiber: 6, cat: 'cereales' },
  { name: 'Son d\'avoine', kcal: 246, protein: 17, carbs: 50, fat: 7, fiber: 15, cat: 'cereales' },
  { name: 'Croissant', kcal: 406, protein: 8, carbs: 46, fat: 21, fiber: 2.6, cat: 'cereales' },
  { name: 'Pain au chocolat', kcal: 414, protein: 7, carbs: 48, fat: 21, fiber: 2.7, cat: 'cereales' },
  { name: 'Crêpe nature', kcal: 190, protein: 6, carbs: 26, fat: 6, fiber: 1, cat: 'cereales' },
  { name: 'Pancake', kcal: 227, protein: 6, carbs: 28, fat: 10, fiber: 1, cat: 'cereales' },
  { name: 'Lentilles corail cuites', kcal: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 5, cat: 'legumineuses' },
  { name: 'Edamame', kcal: 121, protein: 12, carbs: 9, fat: 5, fiber: 5, cat: 'legumineuses' },
  { name: 'Haricots noirs cuits', kcal: 132, protein: 8.9, carbs: 24, fat: 0.5, fiber: 8.7, cat: 'legumineuses' },
  { name: 'Flageolets cuits', kcal: 128, protein: 8, carbs: 22, fat: 0.5, fiber: 7, cat: 'legumineuses' },
  { name: 'Fèves cuites', kcal: 110, protein: 7.6, carbs: 20, fat: 0.4, fiber: 5.4, cat: 'legumineuses' },
  { name: 'Protéine de soja texturée (sèche)', kcal: 336, protein: 50, carbs: 30, fat: 1.5, fiber: 18, cat: 'legumineuses' },
  { name: 'Seitan', kcal: 141, protein: 25, carbs: 4, fat: 2, fiber: 1, cat: 'legumineuses' },
  { name: 'Falafel', kcal: 333, protein: 13, carbs: 32, fat: 18, fiber: 5, cat: 'legumineuses' },
  { name: 'Magret de canard cuit', kcal: 220, protein: 28, carbs: 0, fat: 12, fiber: 0, cat: 'viandes' },
  { name: 'Côte de porc cuite', kcal: 231, protein: 26, carbs: 0, fat: 14, fiber: 0, cat: 'viandes' },
  { name: 'Rôti de veau cuit', kcal: 172, protein: 31, carbs: 0, fat: 5, fiber: 0, cat: 'viandes' },
  { name: 'Gigot d\'agneau cuit', kcal: 230, protein: 26, carbs: 0, fat: 14, fiber: 0, cat: 'viandes' },
  { name: 'Saucisse cuite', kcal: 300, protein: 16, carbs: 1, fat: 26, fiber: 0, cat: 'viandes' },
  { name: 'Merguez cuite', kcal: 290, protein: 15, carbs: 1, fat: 25, fiber: 0, cat: 'viandes' },
  { name: 'Chorizo', kcal: 455, protein: 24, carbs: 2, fat: 38, fiber: 0, cat: 'viandes' },
  { name: 'Bacon grillé', kcal: 541, protein: 37, carbs: 1.4, fat: 42, fiber: 0, cat: 'viandes' },
  { name: 'Jambon de dinde', kcal: 105, protein: 19, carbs: 1.5, fat: 2.5, fiber: 0, cat: 'viandes' },
  { name: 'Poulet rôti avec peau', kcal: 220, protein: 27, carbs: 0, fat: 12, fiber: 0, cat: 'viandes' },
  { name: 'Foie de volaille cuit', kcal: 165, protein: 24, carbs: 1, fat: 6, fiber: 0, cat: 'viandes' },
  { name: 'Steak végétal (soja)', kcal: 180, protein: 17, carbs: 8, fat: 8, fiber: 4, cat: 'viandes' },
  { name: 'Omelette', kcal: 154, protein: 11, carbs: 1, fat: 12, fiber: 0, cat: 'viandes' },
  { name: 'Nuggets de poulet', kcal: 296, protein: 15, carbs: 16, fat: 19, fiber: 1, cat: 'viandes' },
  { name: 'Colin / lieu cuit', kcal: 100, protein: 23, carbs: 0, fat: 1, fiber: 0, cat: 'poissons' },
  { name: 'Dorade cuite', kcal: 130, protein: 22, carbs: 0, fat: 4.5, fiber: 0, cat: 'poissons' },
  { name: 'Bar cuit', kcal: 124, protein: 24, carbs: 0, fat: 2.5, fiber: 0, cat: 'poissons' },
  { name: 'Tilapia cuit', kcal: 128, protein: 26, carbs: 0, fat: 2.7, fiber: 0, cat: 'poissons' },
  { name: 'Sole cuite', kcal: 117, protein: 24, carbs: 0, fat: 1.5, fiber: 0, cat: 'poissons' },
  { name: 'Hareng fumé', kcal: 250, protein: 22, carbs: 0, fat: 18, fiber: 0, cat: 'poissons' },
  { name: 'Saumon fumé', kcal: 180, protein: 25, carbs: 0, fat: 9, fiber: 0, cat: 'poissons' },
  { name: 'Surimi', kcal: 95, protein: 8, carbs: 12, fat: 1, fiber: 0, cat: 'poissons' },
  { name: 'Moules cuites', kcal: 172, protein: 24, carbs: 7, fat: 4.5, fiber: 0, cat: 'poissons' },
  { name: 'Huitres', kcal: 68, protein: 7, carbs: 4, fat: 2, fiber: 0, cat: 'poissons' },
  { name: 'Calamars cuits', kcal: 175, protein: 18, carbs: 8, fat: 7, fiber: 0, cat: 'poissons' },
  { name: 'Anchois à l\'huile', kcal: 210, protein: 29, carbs: 0, fat: 10, fiber: 0, cat: 'poissons' },
  { name: 'Lait écrémé', kcal: 34, protein: 3.4, carbs: 5, fat: 0.1, fiber: 0, cat: 'laitiers' },
  { name: 'Yaourt grec 5%', kcal: 97, protein: 9, carbs: 4, fat: 5, fiber: 0, cat: 'laitiers' },
  { name: 'Petit-suisse', kcal: 140, protein: 9, carbs: 3.5, fat: 10, fiber: 0, cat: 'laitiers' },
  { name: 'Kéfir', kcal: 41, protein: 3.3, carbs: 4.5, fat: 1, fiber: 0, cat: 'laitiers' },
  { name: 'Ricotta', kcal: 174, protein: 11, carbs: 3, fat: 13, fiber: 0, cat: 'laitiers' },
  { name: 'Feta', kcal: 264, protein: 14, carbs: 4, fat: 21, fiber: 0, cat: 'laitiers' },
  { name: 'Chèvre frais', kcal: 268, protein: 18, carbs: 2.5, fat: 21, fiber: 0, cat: 'laitiers' },
  { name: 'Camembert', kcal: 300, protein: 20, carbs: 0.5, fat: 24, fiber: 0, cat: 'laitiers' },
  { name: 'Emmental', kcal: 380, protein: 28, carbs: 1.5, fat: 29, fiber: 0, cat: 'laitiers' },
  { name: 'Fromage râpé', kcal: 400, protein: 26, carbs: 1, fat: 32, fiber: 0, cat: 'laitiers' },
  { name: 'Mascarpone', kcal: 430, protein: 4, carbs: 4, fat: 44, fiber: 0, cat: 'laitiers' },
  { name: 'Crème fraîche 30%', kcal: 292, protein: 2.4, carbs: 3, fat: 30, fiber: 0, cat: 'laitiers' },
  { name: 'Crème légère 15%', kcal: 160, protein: 2.8, carbs: 4, fat: 15, fiber: 0, cat: 'laitiers' },
  { name: 'Crème de soja', kcal: 175, protein: 3, carbs: 2, fat: 17, fiber: 0, cat: 'laitiers' },
  { name: 'Lait de coco', kcal: 197, protein: 2, carbs: 3, fat: 21, fiber: 0, cat: 'laitiers' },
  { name: 'Beurre allégé', kcal: 400, protein: 3, carbs: 1, fat: 42, fiber: 0, cat: 'laitiers' },
  { name: 'Poireau cuit', kcal: 31, protein: 0.9, carbs: 6, fat: 0.2, fiber: 1.8, cat: 'legumes' },
  { name: 'Céleri branche', kcal: 16, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, cat: 'legumes' },
  { name: 'Céleri-rave cuit', kcal: 27, protein: 1.2, carbs: 5, fat: 0.2, fiber: 1.8, cat: 'legumes' },
  { name: 'Chou rouge', kcal: 31, protein: 1.4, carbs: 7, fat: 0.2, fiber: 2.1, cat: 'legumes' },
  { name: 'Chou vert cuit', kcal: 33, protein: 2, carbs: 5, fat: 0.4, fiber: 3, cat: 'legumes' },
  { name: 'Endive', kcal: 17, protein: 0.9, carbs: 3.4, fat: 0.1, fiber: 3.1, cat: 'legumes' },
  { name: 'Radis', kcal: 16, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.6, cat: 'legumes' },
  { name: 'Betterave cuite', kcal: 44, protein: 1.7, carbs: 10, fat: 0.2, fiber: 2, cat: 'legumes' },
  { name: 'Navet cuit', kcal: 22, protein: 0.7, carbs: 5, fat: 0.1, fiber: 2, cat: 'legumes' },
  { name: 'Fenouil', kcal: 31, protein: 1.2, carbs: 7, fat: 0.2, fiber: 3.1, cat: 'legumes' },
  { name: 'Asperges cuites', kcal: 22, protein: 2.4, carbs: 4, fat: 0.2, fiber: 2.1, cat: 'legumes' },
  { name: 'Artichaut cuit', kcal: 47, protein: 3.3, carbs: 11, fat: 0.2, fiber: 8.6, cat: 'legumes' },
  { name: 'Maïs doux', kcal: 96, protein: 3.4, carbs: 21, fat: 1.5, fiber: 2.4, cat: 'legumes' },
  { name: 'Potiron cuit', kcal: 26, protein: 1, carbs: 6, fat: 0.1, fiber: 1.1, cat: 'legumes' },
  { name: 'Courge butternut cuite', kcal: 40, protein: 0.9, carbs: 10, fat: 0.1, fiber: 2, cat: 'legumes' },
  { name: 'Roquette', kcal: 25, protein: 2.6, carbs: 3.7, fat: 0.7, fiber: 1.6, cat: 'legumes' },
  { name: 'Mâche', kcal: 21, protein: 2, carbs: 3.6, fat: 0.4, fiber: 1.5, cat: 'legumes' },
  { name: 'Poivron vert', kcal: 20, protein: 0.9, carbs: 4.6, fat: 0.2, fiber: 1.7, cat: 'legumes' },
  { name: 'Olives vertes', kcal: 145, protein: 1, carbs: 3.8, fat: 15, fiber: 3.3, cat: 'legumes' },
  { name: 'Olives noires', kcal: 235, protein: 1.8, carbs: 6, fat: 22, fiber: 3.2, cat: 'legumes' },
  { name: 'Cornichons', kcal: 12, protein: 0.6, carbs: 2.3, fat: 0.2, fiber: 1.2, cat: 'legumes' },
  { name: 'Choucroute cuite', kcal: 19, protein: 0.9, carbs: 4, fat: 0.1, fiber: 2.9, cat: 'legumes' },
  { name: 'Algues nori', kcal: 35, protein: 6, carbs: 5, fat: 0.3, fiber: 0.3, cat: 'legumes' },
  { name: 'Abricot', kcal: 48, protein: 1.4, carbs: 11, fat: 0.4, fiber: 2, cat: 'fruits' },
  { name: 'Pêche', kcal: 39, protein: 0.9, carbs: 10, fat: 0.3, fiber: 1.5, cat: 'fruits' },
  { name: 'Nectarine', kcal: 44, protein: 1.1, carbs: 11, fat: 0.3, fiber: 1.7, cat: 'fruits' },
  { name: 'Prune', kcal: 46, protein: 0.7, carbs: 11, fat: 0.3, fiber: 1.4, cat: 'fruits' },
  { name: 'Cerises', kcal: 63, protein: 1, carbs: 16, fat: 0.2, fiber: 2.1, cat: 'fruits' },
  { name: 'Melon', kcal: 34, protein: 0.8, carbs: 8, fat: 0.2, fiber: 0.9, cat: 'fruits' },
  { name: 'Citron', kcal: 29, protein: 1.1, carbs: 9, fat: 0.3, fiber: 2.8, cat: 'fruits' },
  { name: 'Pamplemousse', kcal: 42, protein: 0.8, carbs: 11, fat: 0.1, fiber: 1.6, cat: 'fruits' },
  { name: 'Grenade', kcal: 83, protein: 1.7, carbs: 19, fat: 1.2, fiber: 4, cat: 'fruits' },
  { name: 'Figue fraîche', kcal: 74, protein: 0.8, carbs: 19, fat: 0.3, fiber: 2.9, cat: 'fruits' },
  { name: 'Figues sèches', kcal: 249, protein: 3.3, carbs: 64, fat: 0.9, fiber: 9.3, cat: 'fruits' },
  { name: 'Abricots secs', kcal: 241, protein: 3.4, carbs: 63, fat: 0.5, fiber: 7.3, cat: 'fruits' },
  { name: 'Pruneaux', kcal: 240, protein: 2.2, carbs: 64, fat: 0.4, fiber: 7.1, cat: 'fruits' },
  { name: 'Raisins secs', kcal: 299, protein: 3.1, carbs: 79, fat: 0.5, fiber: 3.7, cat: 'fruits' },
  { name: 'Cranberries séchées', kcal: 308, protein: 0.1, carbs: 82, fat: 1.4, fiber: 5.7, cat: 'fruits' },
  { name: 'Mûres', kcal: 43, protein: 1.4, carbs: 10, fat: 0.5, fiber: 5.3, cat: 'fruits' },
  { name: 'Cassis', kcal: 63, protein: 1.4, carbs: 15, fat: 0.4, fiber: 6.8, cat: 'fruits' },
  { name: 'Noix de coco fraîche', kcal: 354, protein: 3.3, carbs: 15, fat: 33, fiber: 9, cat: 'fruits' },
  { name: 'Fruits rouges surgelés', kcal: 45, protein: 1, carbs: 8, fat: 0.4, fiber: 4, cat: 'fruits' },
  { name: 'Banane plantain cuite', kcal: 116, protein: 0.8, carbs: 31, fat: 0.2, fiber: 2.3, cat: 'fruits' },
  { name: 'Noisettes', kcal: 628, protein: 15, carbs: 17, fat: 61, fiber: 9.7, cat: 'noix_graines' },
  { name: 'Pistaches', kcal: 560, protein: 20, carbs: 28, fat: 45, fiber: 10, cat: 'noix_graines' },
  { name: 'Noix de pécan', kcal: 691, protein: 9, carbs: 14, fat: 72, fiber: 9.6, cat: 'noix_graines' },
  { name: 'Noix du Brésil', kcal: 659, protein: 14, carbs: 12, fat: 67, fiber: 7.5, cat: 'noix_graines' },
  { name: 'Noix de macadamia', kcal: 718, protein: 8, carbs: 14, fat: 76, fiber: 8.6, cat: 'noix_graines' },
  { name: 'Graines de tournesol', kcal: 584, protein: 21, carbs: 20, fat: 51, fiber: 8.6, cat: 'noix_graines' },
  { name: 'Graines de sésame', kcal: 573, protein: 18, carbs: 23, fat: 50, fiber: 11.8, cat: 'noix_graines' },
  { name: 'Pignons de pin', kcal: 673, protein: 14, carbs: 13, fat: 68, fiber: 3.7, cat: 'noix_graines' },
  { name: 'Purée d\'amande', kcal: 614, protein: 21, carbs: 19, fat: 56, fiber: 10, cat: 'noix_graines' },
  { name: 'Tahini', kcal: 595, protein: 17, carbs: 21, fat: 54, fiber: 9, cat: 'noix_graines' },
  { name: 'Noix de coco râpée', kcal: 660, protein: 6.9, carbs: 24, fat: 65, fiber: 16, cat: 'noix_graines' },
  { name: 'Huile de tournesol', kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, cat: 'huiles' },
  { name: 'Huile de coco', kcal: 892, protein: 0, carbs: 0, fat: 99, fiber: 0, cat: 'huiles' },
  { name: 'Margarine', kcal: 717, protein: 0.2, carbs: 0.7, fat: 80, fiber: 0, cat: 'huiles' },
  { name: 'Mayonnaise', kcal: 680, protein: 1, carbs: 1.3, fat: 75, fiber: 0, cat: 'huiles' },
  { name: 'Vinaigrette', kcal: 450, protein: 0.5, carbs: 6, fat: 47, fiber: 0, cat: 'huiles' },
  { name: 'Sauce tomate', kcal: 35, protein: 1.4, carbs: 6, fat: 0.6, fiber: 1.5, cat: 'condiments' },
  { name: 'Coulis de tomate', kcal: 30, protein: 1.3, carbs: 5, fat: 0.3, fiber: 1.2, cat: 'condiments' },
  { name: 'Pesto', kcal: 450, protein: 5, carbs: 6, fat: 45, fiber: 2, cat: 'condiments' },
  { name: 'Sirop d\'érable', kcal: 260, protein: 0, carbs: 67, fat: 0.1, fiber: 0, cat: 'condiments' },
  { name: 'Sucre', kcal: 400, protein: 0, carbs: 100, fat: 0, fiber: 0, cat: 'condiments' },
  { name: 'Cassonade', kcal: 380, protein: 0, carbs: 98, fat: 0, fiber: 0, cat: 'condiments' },
  { name: 'Vinaigre balsamique', kcal: 88, protein: 0.5, carbs: 17, fat: 0, fiber: 0, cat: 'condiments' },
  { name: 'Sriracha', kcal: 93, protein: 1.9, carbs: 19, fat: 0.9, fiber: 2.2, cat: 'condiments' },
  { name: 'Harissa', kcal: 130, protein: 4, carbs: 12, fat: 7, fiber: 6, cat: 'condiments' },
  { name: 'Levure maltée', kcal: 385, protein: 50, carbs: 36, fat: 5, fiber: 27, cat: 'condiments' },
  { name: 'Café noir', kcal: 2, protein: 0.1, carbs: 0, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Thé infusé', kcal: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Jus d\'orange', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, cat: 'boissons' },
  { name: 'Jus de pomme', kcal: 46, protein: 0.1, carbs: 11, fat: 0.1, fiber: 0.2, cat: 'boissons' },
  { name: 'Cola', kcal: 42, protein: 0, carbs: 10.6, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Soda light', kcal: 0.3, protein: 0, carbs: 0, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Bière blonde', kcal: 43, protein: 0.5, carbs: 3.6, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Vin rouge', kcal: 85, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Vin blanc', kcal: 82, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Boisson énergisante', kcal: 45, protein: 0.4, carbs: 11, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Smoothie aux fruits', kcal: 55, protein: 0.7, carbs: 13, fat: 0.2, fiber: 1, cat: 'boissons' },
  { name: 'Boisson isotonique', kcal: 26, protein: 0, carbs: 6.4, fat: 0, fiber: 0, cat: 'boissons' },
  { name: 'Pizza margherita', kcal: 266, protein: 11, carbs: 33, fat: 10, fiber: 2.3, cat: 'divers' },
  { name: 'Maki saumon', kcal: 145, protein: 6, carbs: 25, fat: 2, fiber: 0.8, cat: 'divers' },
  { name: 'Quiche lorraine', kcal: 300, protein: 10, carbs: 22, fat: 19, fiber: 1, cat: 'divers' },
  { name: 'Sandwich jambon-beurre', kcal: 250, protein: 10, carbs: 30, fat: 10, fiber: 2, cat: 'divers' },
  { name: 'Lasagnes', kcal: 130, protein: 8, carbs: 12, fat: 5, fiber: 1.2, cat: 'divers' },
  { name: 'Hachis parmentier', kcal: 110, protein: 6, carbs: 12, fat: 4, fiber: 1.3, cat: 'divers' },
  { name: 'Riz cantonais', kcal: 160, protein: 6, carbs: 22, fat: 5, fiber: 1, cat: 'divers' },
  { name: 'Soupe de légumes', kcal: 40, protein: 1.2, carbs: 6, fat: 1, fiber: 1.5, cat: 'divers' },
  { name: 'Glace vanille', kcal: 207, protein: 3.5, carbs: 24, fat: 11, fiber: 0.7, cat: 'divers' },
  { name: 'Yaourt glacé', kcal: 130, protein: 4, carbs: 24, fat: 2, fiber: 0, cat: 'divers' },
  { name: 'Biscuits secs', kcal: 450, protein: 7, carbs: 70, fat: 16, fiber: 2.5, cat: 'divers' },
  { name: 'Madeleine', kcal: 450, protein: 6, carbs: 50, fat: 25, fiber: 1, cat: 'divers' },
  { name: 'Barre de céréales', kcal: 400, protein: 6, carbs: 70, fat: 10, fiber: 3, cat: 'divers' },
  { name: 'Popcorn nature', kcal: 387, protein: 13, carbs: 78, fat: 4.5, fiber: 15, cat: 'divers' },
  { name: 'Gaufre', kcal: 290, protein: 7, carbs: 33, fat: 14, fiber: 1.5, cat: 'divers' },
];
