// Shared between the daily dashboard (today's micronutrient totals) and the weekly Rapport
// (period averages), so the two views never diverge on what "58%" or "orange" means.
// kind: 'limit' marks nutrients where the health concern is going OVER the reference value
// (sodium, caffeine) rather than staying under it, like every other (default 'floor') nutrient —
// these are shown in their own isolated "seuils max" section with inverted logic (low = good).
// weeklyAvg: true marks fat-soluble vitamins + B12, which the body stores over weeks/months —
// a single day's value isn't physiologically meaningful, so the dashboard shows a 7-day average
// for these instead of today's number.
// dailyGoal: false marks nutrients with no meaningful *daily* target — either stored over weeks
// (fat-soluble vitamins, B12) or naturally consumed in occasional/lumpy amounts rather than a
// steady daily need (omega-3, folate, selenium, iodine, choline). These get a weekly target
// (reference × 7) instead — see "Semaine en cours"/"Semaine passée". Defaults to true.
// excess: how to explain a >150% reading — 'water' (eliminated, no real risk), 'fat'
// (can accumulate, worth keeping an eye on), 'mineral' (generally fine short-term, but sustained
// high intake is worth watching). Only applies to 'floor' nutrients (limit ones already have
// their own over-threshold framing).
export const MICRO_REFERENCE = {
  fiber: { label: 'Fibres', unit: 'g', reference: 30, excess: 'mineral' },
  sodium: { label: 'Sodium', unit: 'mg', reference: 2300, kind: 'limit' },
  potassium: { label: 'Potassium', unit: 'mg', reference: 3500, excess: 'water' },
  magnesium: { label: 'Magnésium', unit: 'mg', reference: 400, excess: 'mineral' },
  calcium: { label: 'Calcium', unit: 'mg', reference: 1000, excess: 'mineral' },
  zinc: { label: 'Zinc', unit: 'mg', reference: 11, excess: 'mineral' },
  iron: { label: 'Fer', unit: 'mg', reference: 8, excess: 'mineral' },
  selenium: { label: 'Sélénium', unit: 'µg', reference: 55, excess: 'mineral', dailyGoal: false },
  iodine: { label: 'Iode', unit: 'µg', reference: 150, excess: 'mineral', dailyGoal: false },
  vitamin_c: { label: 'Vitamine C', unit: 'mg', reference: 90, excess: 'water' },
  vitamin_a: { label: 'Vitamine A', unit: 'µg', reference: 900, weeklyAvg: true, excess: 'fat', dailyGoal: false },
  vitamin_d: { label: 'Vitamine D', unit: 'UI', reference: 800, rangeLabel: '800–2000 UI', weeklyAvg: true, excess: 'fat', dailyGoal: false },
  vitamin_e: { label: 'Vitamine E', unit: 'mg', reference: 15, weeklyAvg: true, excess: 'fat', dailyGoal: false },
  vitamin_k: { label: 'Vitamine K', unit: 'µg', reference: 120, weeklyAvg: true, excess: 'fat', dailyGoal: false },
  folate: { label: 'Folates (B9)', unit: 'µg', reference: 400, excess: 'water', dailyGoal: false },
  b12: { label: 'Vitamine B12', unit: 'µg', reference: 2.4, weeklyAvg: true, excess: 'water', dailyGoal: false },
  choline: { label: 'Choline', unit: 'mg', reference: 550, excess: 'water', dailyGoal: false },
  // Marine EPA/DHA only, never plant ALA — same rule the AI estimation follows (see
  // omega3Reference.js). The note explains the absence of flax and walnuts from the food list,
  // which is otherwise the first thing anyone asks.
  omega3: {
    label: 'Oméga-3 (EPA/DHA)',
    unit: 'mg',
    reference: 500,
    excess: 'mineral',
    dailyGoal: false,
    note: "Seuls le poisson, les fruits de mer, les œufs et les algues contiennent de l'EPA/DHA. Le lin, les noix, le chia et l'huile de colza apportent de l'ALA, que le corps ne convertit qu'à quelques pour cent — ils comptent donc 0 ici.",
  },
  caffeine: { label: 'Caféine', unit: 'mg', reference: 300, kind: 'limit' },
};

export function hasDailyGoal(key) {
  return MICRO_REFERENCE[key]?.dailyGoal !== false;
}

// One-line food suggestion per nutrient, used to auto-generate "what to do about it" for any
// floor nutrient under 80% of its target (dashboard "À améliorer" section and the weekly Rapport).
export const NUTRIENT_SUGGESTIONS = {
  fiber: 'des légumineuses, flocons d\'avoine, légumes ou fruits',
  potassium: "une pomme de terre avec la peau (300 g ≈ 900 mg) ou une poignée d'épinards",
  magnesium: '30 g d\'amandes (≈ 75 mg), des épinards, du chocolat noir ou des graines de courge',
  calcium: 'un laitage, 100 g de sardines, 30 g d\'amandes ou du tofu',
  zinc: 'de la viande rouge, des fruits de mer, des œufs ou des graines de courge',
  iron: '100 g de lentilles cuites (≈ 3 mg) ou un steak de bœuf',
  selenium: 'une noix du Brésil (≈ 70-90 µg)',
  iodine: "du poisson, du sel iodé ou des produits laitiers",
  vitamin_c: "un kiwi ou la moitié d'un poivron rouge (≈ 70-90 mg)",
  vitamin_a: 'de la patate douce, des carottes, des épinards ou du foie',
  vitamin_d: 'du poisson gras, des œufs, ou une supplémentation',
  vitamin_e: 'des huiles végétales, des amandes ou des graines de tournesol',
  vitamin_k: 'des légumes verts à feuilles (épinards, chou kale)',
  folate: 'des légumes verts à feuilles, des légumineuses ou de l\'avocat',
  b12: 'un œuf ou 100 g de viande/poisson (≈ 1-3 µg)',
  choline: 'un œuf entier (≈ 150 mg)',
  omega3: 'du saumon, du maquereau, des sardines, ou un complément d\'huile de poisson/algue (EPA/DHA — les noix et l\'huile de colza/lin apportent de l\'ALA, pas de l\'EPA/DHA)',
};

// Nutrients where a supplement is a realistic, commonly-recommended option when diet alone
// falls short — shown as "compléments à envisager" alongside the food-based suggestions above.
// Deliberately short list: only nutrients that are genuinely hard to hit from food alone for
// many diets (fatty fish/dairy-light diets, etc.), not every deficient nutrient.
export const SUPPLEMENT_SUGGESTIONS = {
  vitamin_d: 'une supplémentation en vitamine D (surtout en automne/hiver — avis médical recommandé)',
  b12: 'un supplément de B12, surtout si l\'alimentation est pauvre en produits animaux',
  omega3: 'un complément d\'huile de poisson ou d\'huile d\'algue (EPA/DHA)',
  iodine: 'un sel iodé ou un complément si le poisson/les produits laitiers sont rares dans l\'alimentation',
};

// Note shown next to a floor nutrient's bar once it's well past 100% (>150%), so a high number
// isn't left unexplained. Water-soluble excess is eliminated in urine (no real accumulation
// risk); fat-soluble can build up over weeks/months; minerals sit in between — usually fine
// short-term but worth not making a daily habit.
export const EXCESS_MESSAGES = {
  water: 'Excès éliminé dans les urines — pas de risque connu à cette dose.',
  fat: 'Vitamine liposoluble : peut s\'accumuler dans le corps sur la durée — à surveiller si ça se répète.',
  mineral: 'Généralement sans risque ponctuellement — à surveiller si c\'est systématique sur plusieurs jours.',
};

// Floor nutrients: <50% = loin de la cible (rouge), 50-80% = à améliorer (orange), 80%+ = ok
// (vert). No separate "too high" tier anymore — a floor nutrient being generously covered isn't
// a problem the way a limit nutrient going over is (see EXCESS_MESSAGES for genuinely high values).
export function microStatus(pct, kind) {
  if (kind === 'limit') {
    if (pct > 100) return 'danger';
    if (pct > 80) return 'warn';
    return 'ok';
  }
  if (pct < 50) return 'low';
  if (pct < 80) return 'warn';
  return 'ok';
}

// How "concerning" an entry is, so both kinds sort worst-first in the same list:
// far below target (floor) or far past the limit (ceiling) both score high.
function severity(pct, kind) {
  return kind === 'limit' ? pct : 100 - pct;
}

export function buildMicroList(nutrientKeys, avgFn) {
  return nutrientKeys
    .filter((k) => MICRO_REFERENCE[k])
    .map((key) => {
      const ref = MICRO_REFERENCE[key];
      const kind = ref.kind || 'floor';
      const value = avgFn(key);
      const pct = (value / ref.reference) * 100;
      const entry = {
        key,
        label: ref.label,
        unit: ref.unit,
        rangeLabel: ref.rangeLabel,
        kind,
        avg: value,
        reference: ref.reference,
        pct,
        status: microStatus(pct, kind),
        weeklyAvg: !!ref.weeklyAvg,
        dailyGoal: hasDailyGoal(key),
      };
      if (kind === 'floor' && pct < 80) {
        entry.suggestion = NUTRIENT_SUGGESTIONS[key] || null;
      }
      if (kind === 'floor' && pct > 150) {
        entry.excessType = ref.excess || 'mineral';
        entry.excessMessage = EXCESS_MESSAGES[entry.excessType];
      }
      return entry;
    })
    .sort((a, b) => severity(b.pct, b.kind) - severity(a.pct, a.kind));
}

// Curated list of common foods with typical micronutrient values per 100 g, used to power the
// "Aliments riches en ..." page for nutrients the user may not have in their personal library.
// Values are ballpark averages from standard food composition tables.
export const COMMON_FOODS = {
  fiber: [
    { name: 'Son de blé', fiber: 43, cat: 'cereales' },
    { name: 'Graines de chia', fiber: 34, cat: 'noix_graines' },
    { name: 'Cacao en poudre non sucré', fiber: 33, cat: 'divers' },
    { name: 'Lin moulu', fiber: 27, cat: 'noix_graines' },
    { name: 'Noix de coco râpée', fiber: 16, cat: 'noix_graines' },
    { name: 'Seigle (farine)', fiber: 15.5, cat: 'cereales' },
    { name: 'Son d\'avoine', fiber: 15, cat: 'cereales' },
    { name: 'Popcorn', fiber: 14.5, cat: 'cereales' },
    { name: 'Amandes', fiber: 12, cat: 'noix_graines' },
    { name: 'Graines de sésame', fiber: 11.8, cat: 'noix_graines' },
    { name: 'Lentilles sèches', fiber: 11, cat: 'legumineuses' },
    { name: 'Chocolat noir (70%)', fiber: 10.9, cat: 'divers' },
    { name: 'Épeautre', fiber: 10.7, cat: 'cereales' },
    { name: 'Haricots blancs', fiber: 10.5, cat: 'legumineuses' },
    { name: 'Fruit de la passion', fiber: 10.4, cat: 'fruits' },
    { name: 'Sarrasin', fiber: 10, cat: 'cereales' },
    { name: 'Flocons d\'avoine', fiber: 10, cat: 'cereales' },
    { name: 'Pistaches', fiber: 10, cat: 'noix_graines' },
    { name: 'Noisettes', fiber: 9.7, cat: 'noix_graines' },
    { name: 'Figues sèches', fiber: 9.3, cat: 'fruits' },
    { name: 'Haricots rouges', fiber: 8.7, cat: 'legumineuses' },
    { name: 'Haricots noirs', fiber: 8.7, cat: 'legumineuses' },
    { name: 'Artichaut', fiber: 8.6, cat: 'legumes' },
    { name: 'Graines de tournesol', fiber: 8.6, cat: 'noix_graines' },
    { name: 'Cacahuètes', fiber: 8.5, cat: 'noix_graines' },
    { name: 'Pois cassés', fiber: 8.3, cat: 'legumineuses' },
    { name: 'Dattes', fiber: 8, cat: 'fruits' },
    { name: 'Lentilles cuites', fiber: 7.9, cat: 'legumineuses' },
    { name: 'Pois chiches', fiber: 7.6, cat: 'legumineuses' },
    { name: 'Abricots secs', fiber: 7.3, cat: 'fruits' },
    { name: 'Pruneaux', fiber: 7.1, cat: 'fruits' },
    { name: 'Flageolets', fiber: 7, cat: 'legumineuses' },
    { name: 'Pain complet', fiber: 7, cat: 'cereales' },
    { name: 'Quinoa', fiber: 7, cat: 'cereales' },
    { name: 'Cassis', fiber: 6.8, cat: 'fruits' },
    { name: 'Avocat', fiber: 6.7, cat: 'fruits' },
    { name: 'Noix', fiber: 6.7, cat: 'noix_graines' },
    { name: 'Framboises', fiber: 6.5, cat: 'fruits' },
    { name: 'Graines de citrouille', fiber: 6, cat: 'noix_graines' },
    { name: 'Fèves', fiber: 5.4, cat: 'legumineuses' },
    { name: 'Goyave', fiber: 5.4, cat: 'fruits' },
    { name: 'Mûres', fiber: 5.3, cat: 'fruits' },
    { name: 'Petits pois', fiber: 5.1, cat: 'legumes' },
    { name: 'Panais', fiber: 4.9, cat: 'legumes' },
    { name: 'Groseilles', fiber: 4.3, cat: 'fruits' },
    { name: 'Chou kale', fiber: 4.1, cat: 'legumes' },
    { name: 'Grenade', fiber: 4, cat: 'fruits' },
    { name: 'Choux de Bruxelles', fiber: 3.8, cat: 'legumes' },
    { name: 'Raisins secs', fiber: 3.7, cat: 'fruits' },
    { name: 'Riz complet', fiber: 3.5, cat: 'cereales' },
    { name: 'Haricots verts', fiber: 3.4, cat: 'legumes' },
    { name: 'Noix de cajou', fiber: 3.3, cat: 'noix_graines' },
    { name: 'Fenouil', fiber: 3.1, cat: 'legumes' },
    { name: 'Poire', fiber: 3.1, cat: 'fruits' },
    { name: 'Aubergine', fiber: 3, cat: 'legumes' },
    { name: 'Patate douce', fiber: 3, cat: 'legumes' },
    { name: 'Kiwi', fiber: 3, cat: 'fruits' },
    { name: 'Carotte', fiber: 2.8, cat: 'legumes' },
    { name: 'Betterave', fiber: 2.8, cat: 'legumes' },
    { name: 'Brocoli', fiber: 2.6, cat: 'legumes' },
    { name: 'Banane', fiber: 2.6, cat: 'fruits' },
    { name: 'Pomme', fiber: 2.4, cat: 'fruits' },
    { name: 'Orange', fiber: 2.4, cat: 'fruits' },
    { name: 'Myrtilles', fiber: 2.4, cat: 'fruits' },
    { name: 'Épinards', fiber: 2.2, cat: 'legumes' },
    { name: 'Asperges', fiber: 2.1, cat: 'legumes' },
    { name: 'Chou-fleur', fiber: 2, cat: 'legumes' },
    { name: 'Courge butternut', fiber: 2, cat: 'legumes' },
    { name: 'Fraises', fiber: 2, cat: 'fruits' },
    { name: 'Poireau', fiber: 1.8, cat: 'legumes' },
    { name: 'Champignons', fiber: 1, cat: 'legumes' },
  ],
  sodium: [
    { name: 'Sel de table', sodium: 38800, cat: 'condiments' },
    { name: 'Bouillon cube', sodium: 20000, cat: 'condiments' },
    { name: 'Sauce soja', sodium: 5700, cat: 'condiments' },
    { name: 'Miso', sodium: 4200, cat: 'condiments' },
    { name: 'Anchois', sodium: 3670, cat: 'poissons' },
    { name: 'Olives', sodium: 2400, cat: 'fruits' },
    { name: 'Câpres', sodium: 2350, cat: 'condiments' },
    { name: 'Saucisson sec', sodium: 1900, cat: 'viandes' },
    { name: 'Roquefort', sodium: 1800, cat: 'laitiers' },
    { name: 'Bacon', sodium: 1700, cat: 'viandes' },
    { name: 'Saumon fumé', sodium: 1700, cat: 'poissons' },
    { name: 'Chorizo', sodium: 1600, cat: 'viandes' },
    { name: 'Parmesan', sodium: 1600, cat: 'laitiers' },
    { name: 'Sauce Worcestershire', sodium: 1500, cat: 'condiments' },
    { name: 'Jambon cru', sodium: 1400, cat: 'viandes' },
    { name: 'Cornichons', sodium: 1200, cat: 'legumes' },
    { name: 'Biscuits apéritif', sodium: 1200, cat: 'divers' },
    { name: 'Moutarde', sodium: 1100, cat: 'condiments' },
    { name: 'Feta', sodium: 1100, cat: 'laitiers' },
    { name: 'Ketchup', sodium: 1000, cat: 'condiments' },
    { name: 'Jambon blanc', sodium: 900, cat: 'viandes' },
    { name: 'Saucisse', sodium: 800, cat: 'viandes' },
    { name: 'Corn flakes', sodium: 700, cat: 'cereales' },
    { name: 'Fromage (cheddar)', sodium: 660, cat: 'laitiers' },
    { name: 'Choucroute', sodium: 660, cat: 'legumes' },
    { name: 'Mozzarella', sodium: 630, cat: 'laitiers' },
    { name: 'Pizza surgelée', sodium: 600, cat: 'divers' },
    { name: 'Chips', sodium: 500, cat: 'divers' },
    { name: 'Pain', sodium: 470, cat: 'cereales' },
    { name: 'Sardines en boîte', sodium: 450, cat: 'poissons' },
    { name: 'Thon en boîte', sodium: 310, cat: 'poissons' },
    { name: 'Soupe en brique', sodium: 300, cat: 'divers' },
    { name: 'Crevettes', sodium: 250, cat: 'poissons' },
  ],
  potassium: [
    { name: 'Haricots blancs', potassium: 1180, cat: 'legumineuses' },
    { name: 'Abricots secs', potassium: 1160, cat: 'fruits' },
    { name: 'Pistaches', potassium: 1025, cat: 'noix_graines' },
    { name: 'Raisins secs', potassium: 749, cat: 'fruits' },
    { name: 'Amandes', potassium: 733, cat: 'noix_graines' },
    { name: 'Pruneaux', potassium: 732, cat: 'fruits' },
    { name: 'Chocolat noir (70%)', potassium: 715, cat: 'divers' },
    { name: 'Figues sèches', potassium: 680, cat: 'fruits' },
    { name: 'Dattes', potassium: 656, cat: 'fruits' },
    { name: 'Graines de tournesol', potassium: 645, cat: 'noix_graines' },
    { name: 'Quinoa', potassium: 563, cat: 'cereales' },
    { name: 'Épinards', potassium: 558, cat: 'legumes' },
    { name: 'Persil', potassium: 554, cat: 'herbes' },
    { name: 'Avocat', potassium: 485, cat: 'fruits' },
    { name: 'Patate douce', potassium: 475, cat: 'legumes' },
    { name: 'Sarrasin', potassium: 460, cat: 'cereales' },
    { name: 'Pomme de terre', potassium: 425, cat: 'legumes' },
    { name: 'Morue', potassium: 413, cat: 'poissons' },
    { name: 'Haricots rouges', potassium: 405, cat: 'legumineuses' },
    { name: 'Saumon', potassium: 380, cat: 'poissons' },
    { name: 'Lentilles', potassium: 369, cat: 'legumineuses' },
    { name: 'Banane', potassium: 358, cat: 'fruits' },
    { name: 'Champignons', potassium: 320, cat: 'legumes' },
    { name: 'Brocoli', potassium: 316, cat: 'legumes' },
    { name: 'Maquereau', potassium: 314, cat: 'poissons' },
    { name: 'Kiwis', potassium: 312, cat: 'fruits' },
    { name: 'Betterave', potassium: 305, cat: 'legumes' },
    { name: 'Courge butternut', potassium: 295, cat: 'legumes' },
    { name: 'Pois chiches', potassium: 291, cat: 'legumineuses' },
    { name: 'Melon', potassium: 267, cat: 'fruits' },
    { name: 'Yaourt', potassium: 240, cat: 'laitiers' },
    { name: 'Tomate', potassium: 237, cat: 'legumes' },
    { name: 'Haricots verts', potassium: 211, cat: 'legumes' },
    { name: 'Orange', potassium: 181, cat: 'fruits' },
    { name: 'Lait', potassium: 150, cat: 'laitiers' },
    { name: 'Tofu', potassium: 121, cat: 'legumineuses' },
  ],
  magnesium: [
    { name: 'Cacao en poudre non sucré', magnesium: 500, cat: 'divers' },
    { name: 'Graines de citrouille', magnesium: 400, cat: 'noix_graines' },
    { name: 'Lin moulu', magnesium: 392, cat: 'noix_graines' },
    { name: 'Noix du Brésil', magnesium: 376, cat: 'noix_graines' },
    { name: 'Graines de sésame', magnesium: 351, cat: 'noix_graines' },
    { name: 'Graines de chia', magnesium: 335, cat: 'noix_graines' },
    { name: 'Graines de tournesol', magnesium: 325, cat: 'noix_graines' },
    { name: 'Amandes', magnesium: 270, cat: 'noix_graines' },
    { name: 'Noix de cajou', magnesium: 260, cat: 'noix_graines' },
    { name: 'Germe de blé', magnesium: 239, cat: 'cereales' },
    { name: 'Sarrasin', magnesium: 231, cat: 'cereales' },
    { name: 'Chocolat noir (70%)', magnesium: 228, cat: 'divers' },
    { name: 'Quinoa', magnesium: 197, cat: 'cereales' },
    { name: 'Haricots blancs', magnesium: 190, cat: 'legumineuses' },
    { name: 'Noisettes', magnesium: 163, cat: 'noix_graines' },
    { name: 'Haricots noirs', magnesium: 160, cat: 'legumineuses' },
    { name: 'Noix', magnesium: 158, cat: 'noix_graines' },
    { name: 'Avoine', magnesium: 138, cat: 'cereales' },
    { name: 'Pistaches', magnesium: 121, cat: 'noix_graines' },
    { name: 'Pain complet', magnesium: 82, cat: 'cereales' },
    { name: 'Bette', magnesium: 81, cat: 'legumes' },
    { name: 'Épinards', magnesium: 79, cat: 'legumes' },
    { name: 'Maquereau', magnesium: 76, cat: 'poissons' },
    { name: 'Figues sèches', magnesium: 68, cat: 'fruits' },
    { name: 'Dattes', magnesium: 54, cat: 'fruits' },
    { name: 'Pois chiches', magnesium: 48, cat: 'legumineuses' },
    { name: 'Lentilles', magnesium: 47, cat: 'legumineuses' },
    { name: 'Moules', magnesium: 34, cat: 'poissons' },
    { name: 'Saumon', magnesium: 31, cat: 'poissons' },
    { name: 'Tofu', magnesium: 30, cat: 'legumineuses' },
    { name: 'Avocat', magnesium: 29, cat: 'fruits' },
    { name: 'Banane', magnesium: 27, cat: 'fruits' },
    { name: 'Yaourt', magnesium: 17, cat: 'laitiers' },
  ],
  calcium: [
    { name: 'Parmesan', calcium: 1180, cat: 'laitiers' },
    { name: 'Graines de sésame', calcium: 980, cat: 'noix_graines' },
    { name: 'Fromage (comté)', calcium: 800, cat: 'laitiers' },
    { name: 'Fromage (cheddar)', calcium: 720, cat: 'laitiers' },
    { name: 'Graines de chia', calcium: 631, cat: 'noix_graines' },
    { name: 'Mozzarella', calcium: 505, cat: 'laitiers' },
    { name: 'Feta', calcium: 493, cat: 'laitiers' },
    { name: 'Sardines (avec arêtes)', calcium: 382, cat: 'poissons' },
    { name: 'Sardines', calcium: 382, cat: 'poissons' },
    { name: 'Tofu (sulfate de calcium)', calcium: 350, cat: 'legumineuses' },
    { name: 'Amandes', calcium: 269, cat: 'noix_graines' },
    { name: 'Lin moulu', calcium: 255, cat: 'noix_graines' },
    { name: 'Anchois', calcium: 232, cat: 'poissons' },
    { name: 'Ricotta', calcium: 207, cat: 'laitiers' },
    { name: 'Figues sèches', calcium: 162, cat: 'fruits' },
    { name: 'Kale', calcium: 150, cat: 'legumes' },
    { name: 'Haricots blancs', calcium: 140, cat: 'legumineuses' },
    { name: 'Persil', calcium: 138, cat: 'herbes' },
    { name: 'Yaourt', calcium: 125, cat: 'laitiers' },
    { name: 'Lait', calcium: 120, cat: 'laitiers' },
    { name: 'Cresson', calcium: 120, cat: 'legumes' },
    { name: 'Boisson végétale enrichie', calcium: 120, cat: 'boissons' },
    { name: 'Noisettes', calcium: 114, cat: 'noix_graines' },
    { name: 'Fromage blanc', calcium: 110, cat: 'laitiers' },
    { name: 'Bok choy', calcium: 105, cat: 'legumes' },
    { name: 'Pois chiches', calcium: 105, cat: 'legumineuses' },
    { name: 'Épinards', calcium: 99, cat: 'legumes' },
    { name: 'Saumon en boîte', calcium: 91, cat: 'poissons' },
    { name: 'Crevettes', calcium: 70, cat: 'poissons' },
    { name: 'Œufs', calcium: 56, cat: 'viandes' },
    { name: 'Brocoli', calcium: 47, cat: 'legumes' },
    { name: 'Oranges', calcium: 40, cat: 'fruits' },
  ],
  zinc: [
    { name: 'Huitres', zinc: 90, cat: 'poissons' },
    { name: 'Germe de blé', zinc: 12.3, cat: 'cereales' },
    { name: 'Graines de sésame', zinc: 7.8, cat: 'noix_graines' },
    { name: 'Graines de citrouille', zinc: 7.5, cat: 'noix_graines' },
    { name: 'Graines de chanvre', zinc: 7.3, cat: 'noix_graines' },
    { name: 'Cacao en poudre non sucré', zinc: 6.8, cat: 'divers' },
    { name: 'Pignons de pin', zinc: 6.5, cat: 'noix_graines' },
    { name: 'Bœuf (steak)', zinc: 6, cat: 'viandes' },
    { name: 'Noix de cajou', zinc: 5.8, cat: 'noix_graines' },
    { name: 'Crabe', zinc: 5.4, cat: 'poissons' },
    { name: 'Foie de bœuf', zinc: 5.3, cat: 'viandes' },
    { name: 'Bœuf haché', zinc: 4.8, cat: 'viandes' },
    { name: 'Agneau', zinc: 4.5, cat: 'viandes' },
    { name: 'Avoine', zinc: 3.6, cat: 'cereales' },
    { name: 'Fromage (cheddar)', zinc: 3.1, cat: 'laitiers' },
    { name: 'Amandes', zinc: 3.1, cat: 'noix_graines' },
    { name: 'Noix', zinc: 3.1, cat: 'noix_graines' },
    { name: 'Moules', zinc: 2.7, cat: 'poissons' },
    { name: 'Porc', zinc: 2.4, cat: 'viandes' },
    { name: 'Quinoa', zinc: 2, cat: 'cereales' },
    { name: 'Dinde', zinc: 1.7, cat: 'viandes' },
    { name: 'Tofu', zinc: 1.6, cat: 'legumineuses' },
    { name: 'Pois chiches', zinc: 1.5, cat: 'legumineuses' },
    { name: 'Haricots rouges', zinc: 1.4, cat: 'legumineuses' },
    { name: 'Lentilles', zinc: 1.3, cat: 'legumineuses' },
    { name: 'Poulet', zinc: 1.3, cat: 'viandes' },
    { name: 'Crevettes', zinc: 1.3, cat: 'poissons' },
    { name: 'Œufs', zinc: 1.3, cat: 'viandes' },
    { name: 'Yaourt', zinc: 0.9, cat: 'laitiers' },
  ],
  iron: [
    { name: 'Palourdes', iron: 28, cat: 'poissons' },
    { name: 'Boudin noir', iron: 20, cat: 'viandes' },
    { name: 'Graines de sésame', iron: 14.6, cat: 'noix_graines' },
    { name: 'Cacao en poudre non sucré', iron: 13.9, cat: 'divers' },
    { name: 'Chocolat noir', iron: 11.9, cat: 'divers' },
    { name: 'Graines de chanvre', iron: 8, cat: 'noix_graines' },
    { name: 'Moules', iron: 6.7, cat: 'poissons' },
    { name: 'Noix de cajou', iron: 6.7, cat: 'noix_graines' },
    { name: 'Foie de bœuf', iron: 6.5, cat: 'viandes' },
    { name: 'Germe de blé', iron: 6.3, cat: 'cereales' },
    { name: 'Persil', iron: 6.2, cat: 'herbes' },
    { name: 'Lin moulu', iron: 5.7, cat: 'noix_graines' },
    { name: 'Huitres', iron: 5.1, cat: 'poissons' },
    { name: 'Avoine', iron: 4.7, cat: 'cereales' },
    { name: 'Pistaches', iron: 3.9, cat: 'noix_graines' },
    { name: 'Haricots blancs', iron: 3.7, cat: 'legumineuses' },
    { name: 'Lentilles', iron: 3.3, cat: 'legumineuses' },
    { name: 'Graines de citrouille', iron: 3.3, cat: 'noix_graines' },
    { name: 'Pois chiches', iron: 2.9, cat: 'legumineuses' },
    { name: 'Sardines', iron: 2.9, cat: 'poissons' },
    { name: 'Épinards', iron: 2.7, cat: 'legumes' },
    { name: 'Tofu', iron: 2.7, cat: 'legumineuses' },
    { name: 'Abricots secs', iron: 2.7, cat: 'fruits' },
    { name: 'Bœuf', iron: 2.6, cat: 'viandes' },
    { name: 'Figues sèches', iron: 2, cat: 'fruits' },
    { name: 'Agneau', iron: 1.8, cat: 'viandes' },
    { name: 'Quinoa', iron: 1.5, cat: 'cereales' },
    { name: 'Dinde', iron: 1.4, cat: 'viandes' },
    { name: 'Betterave', iron: 0.8, cat: 'legumes' },
    { name: 'Brocoli', iron: 0.7, cat: 'legumes' },
  ],
  selenium: [
    { name: 'Noix du Brésil', selenium: 1917, cat: 'noix_graines' },
    { name: 'Germe de blé', selenium: 79, cat: 'cereales' },
    { name: 'Huitres', selenium: 63, cat: 'poissons' },
    { name: 'Thon', selenium: 60, cat: 'poissons' },
    { name: 'Graines de chia', selenium: 55, cat: 'noix_graines' },
    { name: 'Graines de tournesol', selenium: 53, cat: 'noix_graines' },
    { name: 'Sardines', selenium: 53, cat: 'poissons' },
    { name: 'Champignons shiitake', selenium: 46, cat: 'legumes' },
    { name: 'Foie de bœuf', selenium: 40, cat: 'viandes' },
    { name: 'Crevettes', selenium: 40, cat: 'poissons' },
    { name: 'Saumon', selenium: 36, cat: 'poissons' },
    { name: 'Hareng', selenium: 36, cat: 'poissons' },
    { name: 'Dinde', selenium: 35, cat: 'viandes' },
    { name: 'Avoine', selenium: 34, cat: 'cereales' },
    { name: 'Morue', selenium: 33, cat: 'poissons' },
    { name: 'Porc', selenium: 32, cat: 'viandes' },
    { name: 'Œufs', selenium: 30, cat: 'viandes' },
    { name: 'Poulet', selenium: 27, cat: 'viandes' },
    { name: 'Pain complet', selenium: 25, cat: 'cereales' },
    { name: 'Bœuf', selenium: 22, cat: 'viandes' },
    { name: 'Noix de cajou', selenium: 20, cat: 'noix_graines' },
    { name: 'Fromage (cheddar)', selenium: 14, cat: 'laitiers' },
    { name: 'Riz complet', selenium: 10, cat: 'cereales' },
    { name: 'Lentilles', selenium: 8, cat: 'legumineuses' },
  ],
  iodine: [
    { name: 'Sel iodé', iodine: 77000, cat: 'condiments' },
    { name: 'Kombu (algue)', iodine: 1500, cat: 'legumes' },
    { name: 'Églefin', iodine: 250, cat: 'poissons' },
    { name: 'Morue', iodine: 200, cat: 'poissons' },
    { name: 'Wakamé (algue)', iodine: 140, cat: 'legumes' },
    { name: 'Moules', iodine: 140, cat: 'poissons' },
    { name: 'Fruits de mer (mélange)', iodine: 60, cat: 'poissons' },
    { name: 'Huitres', iodine: 60, cat: 'poissons' },
    { name: 'Crevettes', iodine: 41, cat: 'poissons' },
    { name: 'Lait', iodine: 35, cat: 'laitiers' },
    { name: 'Yaourt', iodine: 30, cat: 'laitiers' },
    { name: 'Fromage (cheddar)', iodine: 30, cat: 'laitiers' },
    { name: 'Pain', iodine: 30, cat: 'cereales' },
    { name: 'Œufs', iodine: 24, cat: 'viandes' },
    { name: 'Nori (algue)', iodine: 16, cat: 'legumes' },
    { name: 'Haricots blancs', iodine: 16, cat: 'legumineuses' },
    { name: 'Saumon', iodine: 14, cat: 'poissons' },
    { name: 'Thon', iodine: 12, cat: 'poissons' },
    { name: 'Cranberries', iodine: 2, cat: 'fruits' },
  ],
  vitamin_c: [
    { name: 'Camu camu', vitamin_c: 2000, cat: 'fruits' },
    { name: 'Acérola', vitamin_c: 1700, cat: 'fruits' },
    { name: 'Goyave', vitamin_c: 228, cat: 'fruits' },
    { name: 'Poivron rouge', vitamin_c: 190, cat: 'legumes' },
    { name: 'Poivron jaune', vitamin_c: 183, cat: 'legumes' },
    { name: 'Cassis', vitamin_c: 181, cat: 'fruits' },
    { name: 'Persil', vitamin_c: 133, cat: 'herbes' },
    { name: 'Kiwi', vitamin_c: 90, cat: 'fruits' },
    { name: 'Brocoli', vitamin_c: 89, cat: 'legumes' },
    { name: 'Choux de Bruxelles', vitamin_c: 85, cat: 'legumes' },
    { name: 'Litchi', vitamin_c: 71, cat: 'fruits' },
    { name: 'Papaye', vitamin_c: 61, cat: 'fruits' },
    { name: 'Fraises', vitamin_c: 58, cat: 'fruits' },
    { name: 'Chou rouge', vitamin_c: 57, cat: 'legumes' },
    { name: 'Orange', vitamin_c: 53, cat: 'fruits' },
    { name: 'Citron', vitamin_c: 53, cat: 'fruits' },
    { name: 'Ananas', vitamin_c: 48, cat: 'fruits' },
    { name: 'Chou-fleur', vitamin_c: 48, cat: 'legumes' },
    { name: 'Groseilles', vitamin_c: 41, cat: 'fruits' },
    { name: 'Mangue', vitamin_c: 36, cat: 'fruits' },
    { name: 'Pamplemousse', vitamin_c: 31, cat: 'fruits' },
    { name: 'Épinards', vitamin_c: 28, cat: 'legumes' },
    { name: 'Framboises', vitamin_c: 26, cat: 'fruits' },
    { name: 'Mûres', vitamin_c: 21, cat: 'fruits' },
    { name: 'Pomme de terre', vitamin_c: 20, cat: 'legumes' },
    { name: 'Tomate', vitamin_c: 14, cat: 'legumes' },
    { name: 'Cranberries', vitamin_c: 13, cat: 'fruits' },
  ],
  vitamin_a: [
    { name: 'Huile de foie de morue', vitamin_a: 30000, cat: 'huiles' },
    { name: 'Foie de bœuf', vitamin_a: 10500, cat: 'viandes' },
    { name: 'Foie de volaille', vitamin_a: 3300, cat: 'viandes' },
    { name: 'Carotte', vitamin_a: 835, cat: 'legumes' },
    { name: 'Patate douce', vitamin_a: 709, cat: 'legumes' },
    { name: 'Beurre', vitamin_a: 684, cat: 'laitiers' },
    { name: 'Kale', vitamin_a: 681, cat: 'legumes' },
    { name: 'Courge butternut', vitamin_a: 532, cat: 'legumes' },
    { name: 'Épinards', vitamin_a: 469, cat: 'legumes' },
    { name: 'Laitue romaine', vitamin_a: 436, cat: 'legumes' },
    { name: 'Persil', vitamin_a: 421, cat: 'herbes' },
    { name: 'Melon', vitamin_a: 338, cat: 'fruits' },
    { name: 'Cantaloup', vitamin_a: 338, cat: 'fruits' },
    { name: 'Poivron rouge', vitamin_a: 313, cat: 'legumes' },
    { name: 'Bette', vitamin_a: 306, cat: 'legumes' },
    { name: 'Fromage', vitamin_a: 265, cat: 'laitiers' },
    { name: 'Abricots secs', vitamin_a: 180, cat: 'fruits' },
    { name: 'Œufs', vitamin_a: 140, cat: 'viandes' },
    { name: 'Abricots', vitamin_a: 96, cat: 'fruits' },
    { name: 'Mangue', vitamin_a: 54, cat: 'fruits' },
  ],
  vitamin_d: [
    { name: 'Huile de foie de morue', vitamin_d: 10000, cat: 'huiles' },
    { name: 'Truite', vitamin_d: 635, cat: 'poissons' },
    { name: 'Saumon', vitamin_d: 526, cat: 'poissons' },
    { name: 'Maquereau', vitamin_d: 360, cat: 'poissons' },
    { name: 'Sardines', vitamin_d: 272, cat: 'poissons' },
    { name: 'Hareng', vitamin_d: 220, cat: 'poissons' },
    { name: 'Thon', vitamin_d: 154, cat: 'poissons' },
    { name: 'Champignons shiitake', vitamin_d: 100, cat: 'legumes' },
    { name: 'Œufs', vitamin_d: 82, cat: 'viandes' },
    { name: 'Anchois', vitamin_d: 69, cat: 'poissons' },
    { name: 'Beurre', vitamin_d: 60, cat: 'laitiers' },
    { name: 'Foie de bœuf', vitamin_d: 50, cat: 'viandes' },
    { name: 'Lait enrichi', vitamin_d: 40, cat: 'laitiers' },
    { name: 'Yaourt enrichi', vitamin_d: 40, cat: 'laitiers' },
    { name: 'Œufs (jaune)', vitamin_d: 37, cat: 'viandes' },
    { name: 'Fromage', vitamin_d: 24, cat: 'laitiers' },
  ],
  vitamin_e: [
    { name: 'Huile de germe de blé', vitamin_e: 150, cat: 'huiles' },
    { name: 'Huile de tournesol', vitamin_e: 41, cat: 'huiles' },
    { name: 'Graines de tournesol', vitamin_e: 35, cat: 'noix_graines' },
    { name: 'Amandes', vitamin_e: 25, cat: 'noix_graines' },
    { name: 'Germe de blé', vitamin_e: 17, cat: 'cereales' },
    { name: 'Noisettes', vitamin_e: 15, cat: 'noix_graines' },
    { name: 'Huile d\'olive', vitamin_e: 14, cat: 'huiles' },
    { name: 'Pignons de pin', vitamin_e: 9.3, cat: 'noix_graines' },
    { name: 'Beurre de cacahuète', vitamin_e: 9, cat: 'divers' },
    { name: 'Arachides', vitamin_e: 4.6, cat: 'noix_graines' },
    { name: 'Olives', vitamin_e: 3.8, cat: 'fruits' },
    { name: 'Noix', vitamin_e: 2.6, cat: 'noix_graines' },
    { name: 'Truite', vitamin_e: 2.3, cat: 'poissons' },
    { name: 'Graines de citrouille', vitamin_e: 2.2, cat: 'noix_graines' },
    { name: 'Avocat', vitamin_e: 2.1, cat: 'fruits' },
    { name: 'Épinards', vitamin_e: 2, cat: 'legumes' },
    { name: 'Poivron rouge', vitamin_e: 1.6, cat: 'legumes' },
    { name: 'Brocoli', vitamin_e: 1.5, cat: 'legumes' },
    { name: 'Kale', vitamin_e: 1.5, cat: 'legumes' },
    { name: 'Kiwi', vitamin_e: 1.5, cat: 'fruits' },
    { name: 'Œufs', vitamin_e: 1.1, cat: 'viandes' },
    { name: 'Saumon', vitamin_e: 1.1, cat: 'poissons' },
    { name: 'Mangue', vitamin_e: 0.9, cat: 'fruits' },
  ],
  vitamin_k: [
    { name: 'Persil', vitamin_k: 1640, cat: 'herbes' },
    { name: 'Natto', vitamin_k: 1100, cat: 'legumineuses' },
    { name: 'Bette', vitamin_k: 830, cat: 'legumes' },
    { name: 'Kale', vitamin_k: 817, cat: 'legumes' },
    { name: 'Épinards', vitamin_k: 483, cat: 'legumes' },
    { name: 'Chou vert', vitamin_k: 407, cat: 'legumes' },
    { name: 'Ciboulette', vitamin_k: 297, cat: 'herbes' },
    { name: 'Choux de Bruxelles', vitamin_k: 177, cat: 'legumes' },
    { name: 'Laitue', vitamin_k: 126, cat: 'legumes' },
    { name: 'Roquette', vitamin_k: 109, cat: 'legumes' },
    { name: 'Brocoli', vitamin_k: 101, cat: 'legumes' },
    { name: 'Huile de colza', vitamin_k: 71, cat: 'huiles' },
    { name: 'Pruneaux', vitamin_k: 60, cat: 'fruits' },
    { name: 'Huile d\'olive', vitamin_k: 60, cat: 'huiles' },
    { name: 'Bok choy', vitamin_k: 46, cat: 'legumes' },
    { name: 'Haricots verts', vitamin_k: 43, cat: 'legumes' },
    { name: 'Asperges', vitamin_k: 42, cat: 'legumes' },
    { name: 'Kiwi', vitamin_k: 40, cat: 'fruits' },
    { name: 'Avocat', vitamin_k: 21, cat: 'fruits' },
    { name: 'Fromage (comté)', vitamin_k: 12, cat: 'laitiers' },
    { name: 'Foie de bœuf', vitamin_k: 6, cat: 'viandes' },
  ],
  folate: [
    { name: 'Levure alimentaire', folate: 3000, cat: 'divers' },
    { name: 'Foie de bœuf', folate: 290, cat: 'viandes' },
    { name: 'Germe de blé', folate: 281, cat: 'cereales' },
    { name: 'Arachides', folate: 240, cat: 'noix_graines' },
    { name: 'Graines de tournesol', folate: 227, cat: 'noix_graines' },
    { name: 'Épinards', folate: 194, cat: 'legumes' },
    { name: 'Quinoa', folate: 184, cat: 'cereales' },
    { name: 'Lentilles', folate: 181, cat: 'legumineuses' },
    { name: 'Pois chiches', folate: 172, cat: 'legumineuses' },
    { name: 'Asperges', folate: 149, cat: 'legumes' },
    { name: 'Haricots blancs', folate: 140, cat: 'legumineuses' },
    { name: 'Laitue romaine', folate: 136, cat: 'legumes' },
    { name: 'Haricots rouges', folate: 130, cat: 'legumineuses' },
    { name: 'Betterave', folate: 109, cat: 'legumes' },
    { name: 'Avocat', folate: 81, cat: 'fruits' },
    { name: 'Petits pois', folate: 65, cat: 'legumes' },
    { name: 'Brocoli', folate: 63, cat: 'legumes' },
    { name: 'Choux de Bruxelles', folate: 61, cat: 'legumes' },
    { name: 'Chou-fleur', folate: 57, cat: 'legumes' },
    { name: 'Œufs', folate: 44, cat: 'viandes' },
    { name: 'Mangue', folate: 43, cat: 'fruits' },
    { name: 'Laitue', folate: 38, cat: 'legumes' },
    { name: 'Papaye', folate: 37, cat: 'fruits' },
    { name: 'Haricots verts', folate: 33, cat: 'legumes' },
    { name: 'Orange', folate: 30, cat: 'fruits' },
  ],
  b12: [
    { name: 'Levure alimentaire enrichie', b12: 100, cat: 'divers' },
    { name: 'Palourdes', b12: 98, cat: 'poissons' },
    { name: 'Foie de bœuf', b12: 60, cat: 'viandes' },
    { name: 'Maquereau', b12: 19, cat: 'poissons' },
    { name: 'Huitres', b12: 16, cat: 'poissons' },
    { name: 'Hareng', b12: 14, cat: 'poissons' },
    { name: 'Thon', b12: 11, cat: 'poissons' },
    { name: 'Sardines', b12: 8.9, cat: 'poissons' },
    { name: 'Moules', b12: 8, cat: 'poissons' },
    { name: 'Truite', b12: 5, cat: 'poissons' },
    { name: 'Saumon', b12: 4, cat: 'poissons' },
    { name: 'Fromage (comté)', b12: 3.1, cat: 'laitiers' },
    { name: 'Agneau', b12: 2.7, cat: 'viandes' },
    { name: 'Bœuf', b12: 2.5, cat: 'viandes' },
    { name: 'Crevettes', b12: 1.5, cat: 'poissons' },
    { name: 'Œufs', b12: 1.1, cat: 'viandes' },
    { name: 'Porc', b12: 0.7, cat: 'viandes' },
    { name: 'Yaourt', b12: 0.6, cat: 'laitiers' },
    { name: 'Lait', b12: 0.5, cat: 'laitiers' },
    { name: 'Boisson végétale enrichie', b12: 0.4, cat: 'boissons' },
  ],
  choline: [
    { name: 'Œufs (jaune)', choline: 680, cat: 'viandes' },
    { name: 'Foie de bœuf', choline: 420, cat: 'viandes' },
    { name: 'Œufs', choline: 251, cat: 'viandes' },
    { name: 'Germe de blé', choline: 152, cat: 'cereales' },
    { name: 'Bœuf', choline: 90, cat: 'viandes' },
    { name: 'Dinde', choline: 70, cat: 'viandes' },
    { name: 'Haricots blancs', choline: 66, cat: 'legumineuses' },
    { name: 'Poulet', choline: 65, cat: 'viandes' },
    { name: 'Morue', choline: 65, cat: 'poissons' },
    { name: 'Saumon', choline: 60, cat: 'poissons' },
    { name: 'Soja (tofu)', choline: 60, cat: 'legumineuses' },
    { name: 'Crevettes', choline: 55, cat: 'poissons' },
    { name: 'Graines de tournesol', choline: 55, cat: 'noix_graines' },
    { name: 'Champignons shiitake', choline: 54, cat: 'legumes' },
    { name: 'Amandes', choline: 52, cat: 'noix_graines' },
    { name: 'Cacahuètes', choline: 52, cat: 'noix_graines' },
    { name: 'Quinoa', choline: 43, cat: 'cereales' },
    { name: 'Pois chiches', choline: 43, cat: 'legumineuses' },
    { name: 'Brocoli', choline: 40, cat: 'legumes' },
    { name: 'Choux de Bruxelles', choline: 40, cat: 'legumes' },
    { name: 'Chou-fleur', choline: 39, cat: 'legumes' },
    { name: 'Lait', choline: 38, cat: 'laitiers' },
    { name: 'Yaourt', choline: 15, cat: 'laitiers' },
  ],
  omega3: [
    { name: 'Huile de foie de morue', omega3: 20000, cat: 'huiles' },
    { name: 'Maquereau', omega3: 2500, cat: 'poissons' },
    { name: 'Anchois', omega3: 2100, cat: 'poissons' },
    { name: 'Hareng', omega3: 2000, cat: 'poissons' },
    { name: 'Saumon d\'élevage', omega3: 2000, cat: 'poissons' },
    { name: 'Sardines', omega3: 1500, cat: 'poissons' },
    { name: 'Saumon sauvage', omega3: 1500, cat: 'poissons' },
    { name: 'Saumon fumé', omega3: 1200, cat: 'poissons' },
    { name: 'Truite', omega3: 1000, cat: 'poissons' },
    { name: 'Huile d\'algue', omega3: 1000, cat: 'huiles' },
    { name: 'Thon', omega3: 800, cat: 'poissons' },
    { name: 'Huitres', omega3: 740, cat: 'poissons' },
    { name: 'Moules', omega3: 700, cat: 'poissons' },
    { name: 'Crabe', omega3: 400, cat: 'poissons' },
    { name: 'Crevettes', omega3: 300, cat: 'poissons' },
    { name: 'Thon en boîte', omega3: 300, cat: 'poissons' },
    { name: 'Œufs oméga-3', omega3: 300, cat: 'viandes' },
    { name: 'Palourdes', omega3: 240, cat: 'poissons' },
    { name: 'Morue', omega3: 200, cat: 'poissons' },
    { name: 'Œufs', omega3: 100, cat: 'viandes' },
  ],
  caffeine: [
    { name: 'Café (espresso)', caffeine: 240, cat: 'boissons' },
    { name: 'Cacao en poudre non sucré', caffeine: 230, cat: 'divers' },
    { name: 'Café (filtré)', caffeine: 95, cat: 'boissons' },
    { name: 'Yerba mate', caffeine: 85, cat: 'boissons' },
    { name: 'Chocolat noir (70%)', caffeine: 80, cat: 'divers' },
    { name: 'Café soluble', caffeine: 60, cat: 'boissons' },
    { name: 'Thé noir', caffeine: 47, cat: 'boissons' },
    { name: 'Thé oolong', caffeine: 38, cat: 'boissons' },
    { name: 'Boisson énergisante', caffeine: 32, cat: 'boissons' },
    { name: 'Thé vert', caffeine: 28, cat: 'boissons' },
    { name: 'Chocolat au lait', caffeine: 20, cat: 'divers' },
    { name: 'Thé blanc', caffeine: 15, cat: 'boissons' },
    { name: 'Cola', caffeine: 10, cat: 'boissons' },
    { name: 'Kombucha', caffeine: 8, cat: 'boissons' },
    { name: 'Café décaféiné', caffeine: 3, cat: 'boissons' },
  ],
};

